ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS full_name VARCHAR(256);
ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS created_by UUID;
ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
